import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Questrial } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const visby = localFont({
  src: "../public/fonts/visbycf-bold.otf",
  variable: "--font-visby",
});

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["400", "700"],
});

const questrial = Questrial({
  subsets: ["latin"],
  variable: "--font-questrial",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "UIIW Official Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${visby.variable} ${poppins.variable} ${questrial.variable} antialiased bg-gradient-to-r from-primary-5 to-primary-4`}
      >
        <Navbar />

        {children}
      </body>
    </html>
  );
}
